#!/usr/bin/env perl 
# DDG Command line interface

use strict;
use warnings;
use Term::Cap;
use WWW::DuckDuckGo;
use HTML::Entities qw/decode_entities/;
use Unicode::Escape qw/escape unescape/;
use encoding 'utf-8';


my $duck = WWW::DuckDuckGo->new;
my $debug = 0;
my $query = join(' ', @ARGV); 

# Fancy terminal text formatting (underlining, bolding)
my $t = Tgetent Term::Cap { TERM => undef };
my ($norm, $under, $bold) = map { $t->Tputs($_,1) } qw/me us md/;


print "Your query was: ${bold}$query${norm}\n\n";

# retrieve zero-click information
my $zci = $duck->zeroclickinfo("$query");

# print instant answer results 
print "${bold}DUCKDUCKGO -- INSTANT ANSWER SECTION${norm}\n\n";
print "${under}Heading$norm: " . $zci->heading."\n\n" if $zci->has_heading;
print "${under}The answer is$norm: " . $zci->answer . "\n" if $zci->has_answer;

if ($zci->has_results) {
	print "${under}Results$norm: \n";
	foreach my $item (@{$zci->results}) {
		print "\t First url: " . $item->first_url."\n" if $item->has_first_url;
		print "\t Text: " .$item->text."\n" if $item->has_text;
#		print "\t Result: " . $item->result."\n" if $item->has_result; # Usually just html version the above
	}
	print "\n";
}

print "Answer Type: ". $zci->answer_type."\n" if $zci->has_answer_type and $debug;

print "Type: " . $zci->type . "\n" if $zci->has_type and $debug;
if ($zci->has_type) {
	if ($zci->type =~ m/A/) { 
		#print "Abstract : " . $zci->abstract."\n" if $zci->has_abstract;

		print "Abstract Text -- " if ($debug); 
		print "${under}Description$norm: " . $zci->abstract_text . "\n" if $zci->has_abstract_text;

		print "Abstract source -- " if ($debug); 
		print "${under}Description source$norm: " . $zci->abstract_source."\n" if $zci->has_abstract_source;

		print "Abstract url: " if ($debug); 
		print "${under}Source url$norm: " . $zci->abstract_url."\n" if $zci->has_abstract_url;
	}
	if ($zci->type =~ m/D/) {
		print "${under}Definition$norm: " . unescape(decode_entities($zci->definition))."\n" if $zci->has_definition;
		print "${under}Definition source$norm: " . unescape(decode_entities($zci->definition_url))."\n" if $zci->has_definition_url;

	}
}
print "\n===========================================\n\n";
